services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postresql
    networks:
      - fastfood-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}", "-d", "${DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastfood-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      POSTGRES_DOCKER: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}
    networks:
      - fastfood-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  fastfood-network: