apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres-deployment
    spec:
      containers:
        - name: c-postgres-deployment
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fastfood-config
                  key: DATABASE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: DATABASE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-secret
                  key: DATABASE_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: postgres-pvc